apps:
  - "@vlc"
  - cheese
  - neomutt
  - neovim
  - onedrive
  - qbittorrent
  - thunderbird
  - uwsm
  - vivaldi-stable
  - wezterm
  - yazi
  - zathura
  - zoxide
  - 1password
flatpaks:
  - ch.protonmail.protonmail-bridge
  - com.github.tchx84.Flatseal
  - md.obsidian.Obsidian
  - im.riot.Riot
