- name: Remove firefox if installed
  become: true
  ansible.builtin.dnf:
    name: firefox
    state: absent
    allow_erasing: true
  ignore_errors: yes

- name: Remove kitty if installed
  become: true
  ansible.builtin.dnf:
    name: kitty
    state: absent
    allow_erasing: true
  ignore_errors: yes
