- name: Install library needed for Synology HyperBackupExplorer
  become: true
  ansible.builtin.dnf:
    name: libxcrypt-compat
    state: present

- name: Enable wezterm Copr repository
  become: true
  ansible.builtin.command: dnf copr enable wezfurlong/wezterm-nightly -y

- name: Add Vivaldi repo using template
  become: true
  ansible.builtin.template:
    src: yum.repo.j2
    dest: /etc/yum.repos.d/vivaldi.repo
    mode: '0644'
  vars:
    repo_id: vivaldi
    repo_name: vivaldi
    baseurl: https://repo.vivaldi.com/archive/rpm/x86_64
    gpgcheck: 1
    gpgkey: https://repo.vivaldi.com/archive/linux_signing_key.pub

- name: Install applications
  become: true
  ansible.builtin.dnf:
    name: "{{ apps }}"
    state: present

- name: Ensure Flathub remote exists (system)
  become: true
  ansible.builtin.command:
    cmd: >
      flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps (system)
  become: true
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop: "{{ flatpaks }}"

- name: Apps to connect iPhone
  become: true
  ansible.builtin.dnf:
    name:
      - libimobiledevice-utils
      - fuse
    state: present
