dev_tools: ["@development-tools", cmake, curl, gcc, hugo, make, pkgconfig, openssl-devel]
cli_tools:
  - asciidoctor
  - bat
  - eza
  - fd
  - fzf
  - gh
  - git
  - git-lfs
  - neovim
  - ripgrep
  - ruff
  - ShellCheck
  - stow
  - tldr
  - tmux
  - toolbox
  - wezterm
  - uv
  - yazi
