apps:
  # Base
  - "@core"
  # Media 
  - "@multimedia" 
  - gvfs
  - pavucontrol
  - pipewire
  - pipewire-pulseaudio
  - wireplumber
  # Utilities 
  - brightnessctl
  - dnf-utils
  - dunst
  - fastfetch
  - gnome-keyring
  - htop
  - sddm
  - trash
  - uutils-coreutils
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - xdg-utils
  # Graphics stack
  - libxkbcommon
  - mesa-dri-drivers
  - mesa-vulkan-drivers
  - wayland
  - xorg-x11-server-Xwayland
  # Input and user environment
  - xdg-user-dirs
  # Network
  - NetworkManager
  - NetworkManager-wifi
  # Applications 
  - foot
  - Thunar
  - neovim
  - zathura
  - zathura-pdf-poppler
